name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar paquetes
        run: dotnet restore ./MaquinaCafe.Tests/MaquinaCafe.Tests.csproj

      - name: Compilar proyecto
        run: dotnet build ./MaquinaCafe.Tests/MaquinaCafe.Tests.csproj --no-restore

      - name: Ejecutar pruebas
        run: dotnet test ./MaquinaCafe.Tests/MaquinaCafe.Tests.csproj --no-build